# образ для сборки
image: Ubuntu1804

# окружение
stack: node 16

# ветка git
branches:
  only:
    - master

# кеширование
cache: node_modules

# команда установки зависимостей
install:
  - npm install

# отключаем встроенную в appveyor систему сборки
build: off

# команда сборки
build_script:
  - npm run build   

# скрипт тестирования
# test_script:
  # - npm run lint && npm test 

# скрипт развёртывания
deploy_script: 
- git config --global credential.helper store
- git config --global user.name AppVeyor
- git config --global user.email ci@appveyor.com
- echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
- npx push-dir --dir=dist --branch=gh-pages --force --verbose